config/routes.rb
Rails.application.routes.draw do

  get "accounts/(:date)" => "accounts#index", 
      :constraints => { :date => /\d{4}-\d{2}-\d{2}/ }
  resources :accounts

  root 'accounts#index'

end

app/models/account.rb
class Account < ActiveRecord::Base
	has_and_belongs_to_many :siblings, 
		class_name: "Account", join_table: "account_links",
		foreign_key: "self", association_foreign_key: "other"

	has_many :downvotes, foreign_key: "by_user_id"

	enum is_spammer: [:no, :maybe, :yes]

	scope :created_on, ->(day) { where("created < ? AND created > ?",
	  day.tomorrow.beginning_of_day, day.beginning_of_day)}

	def update_links
		user = Genius::User.new(id: id)
		other_accounts = user.ids_with_same_ip
		all_ids = [id]+other_accounts.map{|i| i.id}
		p all_ids
		other_accounts.each do |other_acct|
			other = Account.find_or_initialize_by id: other_acct.id
			other.name = other_acct.login
			other.is_spammer = self.is_spammer unless other.created_at
			other.save
			siblings << other
		end
		other_accounts.each do |other_acct|
			other = Account.find(other_acct.id)
			other.sibling_ids = all_ids - [other_acct.id]
			other.save
		end
	end
end

app/models/downvote.rb
class Downvote < ActiveRecord::Base
	belongs_to :by_user, class_name: "Account", counter_cache: "downvote_counter"
	belongs_to :of_user, class_name: "Account"
end

# Downvote.where("created_at > ? and created_at < ? and by_user_id > ?",
#     Time.zone.today.beginning_of_day, Time.zone.today.tomorrow.beginning_of_day, 
#     Account.created_on(Time.zone.yesterday).order(:created).first.id).
#   group(:by_user_id).count.sort_by{|k,v|-v}

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index()
    if params[:date]
      @date = Date.strptime(params[:date], '%Y-%m-%d')
    else
      @date = Time.zone.today
    end
    @hours = Hash.new { |hash, key| hash[key] = [] }
    Account.created_on(@date).order(created: :desc, downvote_counter: :asc).each do |e|
      @hours[e.created.strftime '%-l %P'] << e
    end

    #.where.not(is_spammer:0)
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:is_spammer, :name)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

    http_basic_authenticate_with name: "spamgenius", password: ENV["http_pass"]

    protect_from_forgery with: :exception

    def index
        @account = Account.order(:created).first
        render "accounts/show" 
    end
end

app/controllers/downvote_controller.rb
class DownvoteController < ApplicationController



	
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/_form.html.erb
<%= form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :is_spammer %><br>
    <%= f.number_field :is_spammer %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accounts/_hour.html.erb
<table>
  <thead>
    <tr>
      <th>Is spammer</th>
      <th>Name</th>
      <th>Id</th>
      <th>Siblings</th>
      <th>Downvotes</th>
      <th>Connected Social?</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% hour.each do |account| %>
      <tr>
        <td><%= account.is_spammer %></td>
        <td>
          <a href="http://genius.com/<%= account.name %>">
            <%= account.name %>
          </a>
        </td>
        <td><%= account.id %></td>
        <td><%= account.siblings.count %></td>
        <td><%= account.downvotes.count %></td>
        <td><%= account.from_social %></td>
        <td><%= link_to 'Show', account %></td>
        <td><%= link_to 'Edit', edit_account_path(account) %></td>
        <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/accounts/all.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Accounts</h1>

<table>
  <thead>
    <tr>
      <th>Is spammer</th>
      <th>Name</th>
      <th>Id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.is_spammer %></td>
        <td><%= account.name %></td>
        <td><%= account.id %></td>
        <td><%= link_to 'Show', account %></td>
        <td><%= link_to 'Edit', edit_account_path(account) %></td>
        <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', new_account_path %>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>
<h1><%= @date %></h1>
<% @hours.each do |day, i| %>
<h2><%= day %></h2>

<%= render partial: "hour", locals: {hour: i} %>

<br>
<% end -%>

<%= link_to @date.yesterday, "/accounts/#{@date.yesterday}" %>
<%= link_to @date.tomorrow, "/accounts/#{@date.tomorrow}" unless @date.tomorrow.future? %>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Is spammer:</strong>
  <%= @account.is_spammer %>
</p>

<p>
  <strong>Name:</strong>
  <%= @account.name %>
</p>

<p>
  <strong>Id:</strong>
  <%= @account.id %>
</p>

<p>
  <strong>Downvotes:</strong>
  <%= @account.downvotes.size %>
</p>

<p>
  <strong>siblings:</strong>
  <ul>
  <% @account.siblings.each do |i| -%>
  	<li> <a href="genius.com/<%= i.name %>"><%= i.name %></a> (<%= i.id %>)</li>
  <% end -%>
  </ul>
</p>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>

app/views/application/index.html.erb
<h1>Spam-genius</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SpamGenius</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>